[package]
name = "spectrl"
version = "1.0.0"
authors = ["Martin Persson <mnpn03@gmail.com>"]

[dependencies]
clap = "2.29.0"
rand = "0.4.1"
palette = "0.2.1"

[target."cfg(windows)".dependencies]
gtk = "0.3.0"
